name: Run Tests
on:
  push:
jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nationalarchives/dr2-github-actions/.github/actions/run-git-secrets@main
      - uses: nationalarchives/dr2-github-actions/.github/actions/slack-send@main
        if: failure()
        with:
          message: ":warning: Secrets found in repository dr2-dynamo-formatters"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Run tests
        run: sbt scalafmtCheckAll test
